### ISSUE TITLE
Fix for the gibberish bug

### ISSUE THREAD

**Issue by Dhrog** [mrwellmann/Unity-Text-To-Seech-with-Sentis#3]
Thanks for sharing your code. 👍

After applying the changes from bearman, replace this code part in the TestTextTtoSpeech.cs file:

```
// Convert input text to tensor.
    var tokenizedOutput = tokenizerRunner.ExecuteTokenizer(inputText);
    var tokenList = tokenizedOutput.Split(' ').ToList();
    for (int i = tokenList.Count-1; i >=0 ; i--)
    {
        if (tokenList[i] == "")
        {
            tokenList.RemoveAt(i);
        };
    }
    int[] inputValues = tokenList.ToArray().Select(int.Parse).ToArray();
```

Instead of replacing the empty string by a zero, the unrequired tokens now get removed.
An output .wav is attached...

[output.zip](https://github.com/mrwellmann/Sentis-TTS-Test/files/13532838/output.zip)

**Comment by mrwellmann** [comment]
Hi Pepe-Hoschi thanks for your fix. I've been very silent as there are a lot of other things taking my time. I'm still interested and will implement your suggestion as soon as I find some tinkering time.

If you are looking for a ready to deploy offline TTS solution you might want to try Overtone https://assetstore.unity.com/packages/tools/generative-ai/overtone-realistic-ai-offline-text-to-speech-tts-251304. I'm not affiliated with them and did not even buy it but it is what my research turned out to be the best easy to implement offline solution 3 moths ago.

**Comment by mrwellmann** [comment]
Thanks fix worked 💯
